language: node_js
node_js:
- '0.12'
before_script:
deploy:
  on:
    repo: cforlando/fl-vote-org
    branch: master
  provider: heroku
  app: flvote
  api_key:
    secure: caogGKXFMuzvDJrK/tGlmaY0XHJL/AIRyCmGOpImTglYP5mwjOycINE8rTKrHOaFzJ0NAZ4IGcBzTaQxQqzoXlHfBXYqO+oqPtdKbOHy8WqsP6vTTHjxaS4zt1uULHVVg6xLYo2quG0TZgTtsSz4iZSGeWfyl8gdTFtYzkgXSgtD1kYzoxP01vTYhCIZjmLwfrYJpepW1VSYsAaULjUx0mj5uNolBEg0Ze/F5d6b9h0HjR9ts8eXWw4bOm5DzLmkpacyPu0jGatwWm15TcStat959OWOlKAuudHNOqX8dXLZpBwcr5rNGqEQAWzQfHM9ZLV/h7nXURFX2FQOdtfheEYxllB63oKrpXLxn4kznenARjYQpta4kD5eIcFPTxHOibrcUcUVrkcHTHnYf2C5KVL91ccNaEe1OjSqEE441Ge0yrl3ima2sUb8E+kxhMr9VITuvTxX1v7wCvy1WgErg0Ekwc6rn0GqZNo1KutXRvWBTagciv6TeDz4U3GnR4UBjYN2VfHfyfbvtyBu71/e0vB+wi9v9zHiyUlz97AdrVGAScyJaubbsOLTxhRdkCrX7zuMaANz/sK1KkOir2rh0F3BwUVMkWvQqfDpywpbITWOqDDDDLr5hH9XYc5/j8v3AYbMAPCBBRBJDVUNfNXl3iWqsy+J+pZ5vNrFZYwzD5g=
