language: node_js
node_js:
- '0.12'
before_script:
deploy:
  on:
    repo: cforlando/fl-vote-org
    branch: master
  provider: heroku
  app: flvote
  api_key:
    secure: bm15rDOQGx4Nvze2JsEx6cb1bznpIHqwWA5fLS5c9bhiKIJm4sqRHvDz7hP+MPzYEff2DwaA4e6yi0Kcl3/7F2SgOQBVFJmiqUWbO4EQPN9VBTrhUDBrBTJ+91AkHImFJQeK8hv92cEZLx6jFsA/LXKD4n9qudlUEzXWvkplqax7vxzgVsvU28fsVqSUbKiYC8raRo5l0yYTmITyU/40MDvc7+L/AeuJT7CZRHUi5bnb23LzfZCwXvyvIgxrxqUlHnCjVgvFDSIIULzHsq19hgbhhx7IohM6CfQRxmXN1uPLGFrwSYv1FsAgPU3ykpcx55ndF1tEDg7XGgbU0CE7EhQqmsNC5OL+NfCeoSiq7V9XOntTPmXaYic+71kxMDsTJg0yLN5raF08EL/DotnNtqvT+QlYQ4hmLkD40QGszW0+uI2K7LhyGazeFcAGRNsI7AjqbwZgA9hDGHM8hRUHfDNP7WsdfLtyx9pogTgVqtSBlWvhbtB3Yk2S0nXsCY3p7sfK3m8VFhRZi1lHMUJ8CrFhSJBpwzssYMyyT5tR/hQY2YVsocexXoTwEiWNAHMvK4dSo0eQxP1by49jBWbEUeekmrpP7/sil4PBAdp15/9ZV0AdurQBNoINVRJHwNzFs1YOdXr3KwWprxs5aYr/eIswSx8NBcbLt6JP9IL/BZU=
